//recommend
export const SUBMITBANNER = 'SUBMITBANNER'
export const SUBMITHOTREM = 'SUBMITHOTREM'
export const SUBMITFLYUPTOPLIST = 'SUBMITFLYUPTOPLIST'
export const SUBMITNEWSONGTOPLIST = 'SUBMITNEWSONGTOPLIST'
export const SUBMITORIGINTOPLIST = 'SUBMITORIGINTOPLIST'


//player
export const SUBMITSONGDETAIL = 'SUBMITSONGDETAIL'